# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
    push:
        branches:
            - master # Remove this line if your primary branch is "main"
            - main # Remove this line if your primary branch is "master"

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Push
        steps:
            - name: git-checkout
              uses: actions/checkout@v2

            - name: Make envfile
              run: |
                  touch .env
                  echo VITE_OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }} >> .env
                  cat .env

            - name: Use Node.js 18.x
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Install all dependencies
              run: npm install

            - name: Build
              run: npm run build-only   # The build command of your project

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  - path: 'dist/'

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
